ids:
    target: 10
    robot1: 11
    robot2: 12
transforms: 
    # organized as parent:child 
    # (i.e. robot1: camera: T is transform w/ robot1 parent and camera child)
    robot1:
        camera: [0,0,0,0,0,0] # x y z roll pitch yaw
        laser: [0,0,0,0,0,0]
        tag: [0,0,0,0,0,0]
    robot2:
        camera: [0,0,0,0,0,0]
        tag: [0,0,0,0,0,0]