  topics:
  key-teleop:
    topic: cmd_vel_key
    timeout: 0.5
    priority: 10

  pad-teleop:
    topic: cmd_vel_pad
    timeout : 0.5
    priority: 10

  nav:
    topic: cmd_vel_nav
    timeout: 0.5
    priority: 5

  estop:
    topic: cmd_vel_stop
    timeout: 0.0
    priority: 100

